#!/usr/bin/env bash
id=$(terraform output -raw instance_id)
name=$(terraform output -raw instance_name)
echo "Getting instance state for ez_tf_ec2_instance:
  Name       : ${name}
  InstanceId : ${id}
"
echo -n "Instance state: "

aws ec2 describe-instances --instance-ids "${id}" --query 'Reservations[].Instances[].State[].Name' --output text
