#!/usr/bin/env bash
id=$(terraform output -raw instance_id)
name=$(terraform output -raw instance_name)
echo "Starting ez_tf_ec2_instance:
- ${name}
- ${id}
"
aws ec2 start-instances --instance-ids "${id}" --out yaml
